### ISSUE TITLE
CSV export of data

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#1]
- [x] write initial tests
- [x] outline implementation plan

**Comment by onlyjsmith** [comment]
Reviewed needs, have implementation plan: 
- need to extract unique columns from array of responses,
- create CSV from unique columns for every row in responses

**Comment by mosaic141688** [comment]
this look doable

**Comment by onlyjsmith** [comment]
- [ ] write initial tests
- [ ] outline implementation plan

**Comment by onlyjsmith** [comment]
@sbabur - can you check the attached, it's a sample of what we'll be exporting once we've deployed this fix 

Note this in an XLSX version, but it will actually be a CSV file (not possible to attach CSV in here). CSV version of file can be downloaded [here](https://www.dropbox.com/s/h0b2opxufpblvhd/nam_responses_2018-04-10_1028.xlsx?dl=0)

[nam_responses_2018-04-10_1028.xlsx](https://github.com/disarm-platform/user-requests-and-feedback/files/1893747/nam_responses_2018-04-10_1028.xlsx)

**Comment by sbabur** [comment]
@onlyjsmith Pefect! Can you confirm what happens to blank fields - would we see a blank or NULL?

**Comment by onlyjsmith** [comment]
@sbabur will be blank fields

**Comment by onlyjsmith** [comment]
This issue was moved to locational/_tickets#63
