### ISSUE TITLE
geodata loading progress says 'NaN %'

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#10]
The way the files (incl. geodata) are being stored and served has changed, to eventually make it easier for users to manage them. One knock-on is that it's no longer possible to estimate progress as we were doing.

Will either:
- remove the progress calculation and show an indeterminate 'loading' bar/spinner, or 
- change the way server is providing the files to restore the calculation approach

**Comment by onlyjsmith** [comment]
Have fixed with a simpler loading animation.

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith ok to close
