### ISSUE TITLE
Add Head of Household name to Botswana dashboard response points

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#100]
@onlyjsmith @TNgidi Like Namibia, Botswana also wants to see the form field for head of household name when you click on the map response points

**Comment by TNgidi** [comment]
@sbabur Thanks, we will implement this

**Comment by Nicolaidavies** [comment]
@sbabur Head of household name has been added to the response points on config version 1.0.25 on staging.

**Comment by sbabur** [comment]
@Nicolaidavies Looks good, validated. Once dashboard issue resolved can release all 3 together (#99 and #101)

**Comment by sbabur** [comment]
@TNgidi Validated in production, can close
