### ISSUE TITLE
Botswana Dashboard - Unsprayable column modifications

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#101]
@onlyjsmith @Nicolaidavies @TNgidi 

Will need to provide you with the new form first, but summary of changes below

1) Remove "Number of rooms not sprayed" column - this is redundant with "Number of sprayable rooms not sprayed" and will be N/A with new form
2) "Number of rooms not sprayable (N)" - remove "(N)" from label and map to new integer field in form (new form to be provided)
3) Remover "Number of rooms not sprayable (%)" column 
4) Can we round the %'s to 2 decimal points?

![image](https://user-images.githubusercontent.com/37877007/44970278-2901dd80-af51-11e8-9f3a-99c8a81f4a7d.png)

**Comment by Nicolaidavies** [comment]
Hi Sameen,

1. Yes
2. Yes
3. Yes
4. Should be able to do, need to ensure it doesn't have any side effects first.

**Comment by sbabur** [comment]
@Nicolaidavies Thanks Nicolai, 4 we can live without if it causes problems but huge nice to have.

**Comment by Nicolaidavies** [comment]
@sbabur The dashboard has been updated on config version 1.0.25 on staging. All except 4 are done. 

We will probably want to open a separate issue for number 4.

**Comment by sbabur** [comment]
@Nicolaidavies Hi Nicolai, if 4 is not a quick thing we can leave it...what do you think? 

Focusing on 1-3 for now, it looks like not all of the dashboard components are showing. Its missing the summary table, Spray room coverage bar chart and reasons for not spraying room pie chart. I had the same issues when using incognito mode

![screencapture-bwa-app-stage-disarm-io-irs-monitor-2018-09-06-13_46_59](https://user-images.githubusercontent.com/37877007/45155563-b9535300-b1db-11e8-8410-801370e4e438.png)

**Comment by Nicolaidavies** [comment]
@sbabur 

4. will take a bit longer. @TNgidi can you note this please? We might get to it later.

I'll take a look at the charts and try to get them working.

**Comment by Nicolaidavies** [comment]
@sbabur 

I've updated the charts, they were using the old aggregations.

**Comment by sbabur** [comment]
@Nicolaidavies Charts all good now, but I don't see the summary table under the map

**Comment by sbabur** [comment]
![image](https://user-images.githubusercontent.com/37877007/45165228-a436ee00-b1f4-11e8-813b-a64f083ad415.png)

**Comment by Nicolaidavies** [comment]
@sbabur It should be fixed now.

**Comment by sbabur** [comment]
@Nicolaidavies Thank you! Just one more comment - it is missing the "Number of unsprayable rooms visited" column, which would be an aggregation of the field 'unsprayable' 

The column should go here: 
![image](https://user-images.githubusercontent.com/37877007/45211460-a780b700-b292-11e8-8add-0cdaa2b47356.png)

**Comment by sbabur** [comment]
@Nicolaidavies Hey Nicolai - checking in to see if this can be picked back up today. Everything else looks good.

**Comment by Nicolaidavies** [comment]
@sbabur I will look at this asap.

**Comment by Nicolaidavies** [comment]
@sbabur I've added the column now.

Let me know when it's ready for production.

**Comment by sbabur** [comment]
@Nicolaidavies Thanks Nicolai, everything looks great - can move to production.

**Comment by Nicolaidavies** [comment]
@sbabur It's live on production now

**Comment by sbabur** [comment]
@TNgidi  Validated in production, can close
