### ISSUE TITLE
Error while retrieving records

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#103]
@onlyjsmith @TNgidi @Nicolaidavies Hi all - I'm getting an 'Error while retrieving records' error on my computer, which I suspect could have something to do with a chrome update that just happened since it was working fine all week up until now. Still working great on my phone. Any of you experiencing the same issue? Version 69.0.3497.100

![image](https://user-images.githubusercontent.com/37877007/45742514-6ffefc80-bbfa-11e8-9c0c-9a64f9d5e46a.png)

**Comment by TNgidi** [comment]
@sbabur Going to investigate on my side

**Comment by TNgidi** [comment]
![1](https://user-images.githubusercontent.com/36029281/45743402-35965f00-bbfc-11e8-8916-5b929b03168f.png)
@sbabur I am not managing to reproduce it, please try logging out and back in again.

**Comment by sbabur** [comment]
@TNgidi Still experiencing the same issue, both with sameen.babur and test.username...I'll try again later when I am on a different network

**Comment by TNgidi** [comment]
@sbabur okay, I think that will help, I have just tried mine on incognito again and it still worked perfectly and I am on the same version as you (69.0.3497.100).

**Comment by sbabur** [comment]
@TNgidi Seems to be ok now...we can close this

**Comment by TNgidi** [comment]
OK, thanks. Let us know if it pops up again on your side.
