### ISSUE TITLE
drop-down for Plan selector on Monitor page occasionally doesn’t work 

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#11]
Sometimes it shows an empty with no plan options, instead of the plan dates - trying to figure out how to reproduce.

**Comment by onlyjsmith** [comment]
Have identified issue and the fix is quick.

**Comment by onlyjsmith** [comment]
Have found and fixed a small bug. Think this is ready to close? @sbabur

**Comment by sbabur** [comment]
@onlyjsmith ok to close - I have not run into this issue yet but will re-open if I see it
