### ISSUE TITLE
upgrading from 1711.30.6 to 1.0.6 doesn't work 100%

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#13]
We know there were issues with this last year, causing problems for users. We improved the approach considerably towards the end of last year. While deploying this year, we’ve noticed it still doesn’t work 100%. We’re investigating, we've made more progress, but there are still some cases where it's causing problems - please let us know if you have _any_ issues upgrading, even if it subsequently works.

It might be that it works fine for you on this 1.0.6 version, but please let us know if not. We’ve tested it many times, on many different browsers, starting from last year’s 1711.30.6 version - and we’ve had a few cases where it’s failed with a blank screen. 

While we're working on this, here are some temporary fixes (in order of severity). We're not expecting the users to do any of this, they are for **testing the functionality only**:
1. Get on Skype to one of us
2. Use an _Incognito_ (Chrome) or _Private browsing_ (Firefox) tab
3. ‘force reload’ (control+shift+r) in the browser, should force it to re-download the whole app. 
4. open the Chrome dev tools (control+shift+i), find the 'Application' tab at the top, the  'Clear storage' tab on the side, and then 'Clear data'. Then do step 3
5. We can make another release with the offline functionality temporarily removed

**Comment by onlyjsmith** [comment]
@sbabur We've created a `reset_offline` page we're going to release in v1.0.7 (next staging release). Between that and the other work we've done, we should be able to clear up many issues with upgrading.

**Comment by sbabur** [comment]
@onlyjsmith thanks, I did not experience any issues upgrading, but we will be testing on many different devices beginning early May

**Comment by onlyjsmith** [comment]
@sbabur there's now a `reset.html` page for every instance, with a link to it from the loading screen. if the app stops loading, this can help by clearing out the offline mode. You can also get to it by visiting e.g. https://nam.app-stage.disarm.io/reset.html

Related work on #9 (update notification)

**Comment by onlyjsmith** [comment]
@sbabur we said we'd move this to done once #9 was released. It's now on staging, so move this to done.

**Comment by sbabur** [comment]
@onlyjsmith upgrade process is working smoothly - can close this issue

**Comment by onlyjsmith** [comment]
👍
