### ISSUE TITLE
Sub-unit dropdown in data collection form does not display text for selected unit

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#16]
@onlyjsmith 

https://www.useloom.com/share/0af8dd1286224f928e8320926bc80f13 

To replicate:
Select admin unit 1 (area) - admin unit 1 reflects correct org unit text (e.g. 'Tutume' or 'Chobe')
Select admin unit 2 (sub-area) - admin unit 2 reflects text 'Select sub-area' and NOT the actual label of the selection

The selection part does work, its just a matter of the display text

**Comment by onlyjsmith** [comment]
@sbabur thanks - we're taking a look

**Comment by onlyjsmith** [comment]
@sbabur and btw, we can reproduce the bug

**Comment by onlyjsmith** [comment]
@sbabur Have identified the problems and have fixed. Will include in next patch version. It was affecting all instances, so no need for duplicate bug reports if you see elsewhere

**Comment by onlyjsmith** [comment]
Confirm fix is deployed on staging as version `v1.0.8-12-g6567296`

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith ok to close
