### ISSUE TITLE
Add household GPS point color-coding/form summary window to Nam

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#17]
Replicate what is seen in Botswana for the green/red/yellow household coordinates + high-level form summary

**Comment by onlyjsmith** [comment]
@sbabur We'll check what's needed for this, hoping it will be simple. If not, this will need to come later.

**Comment by onlyjsmith** [comment]
@sbabur The colours are based on the form responses. We would need to know from you what are the definitions for each of the following - ideally in terms of the _aggregations_:

### Status/colours (with example aggregations for Botswana in brackets)
- not sprayable/blue: (`n_rooms_material == number_of_rooms`)
- not sprayed/red: (`any_sprayed == 'no'`)
- partial/yellow: (`number_of_rooms > number_sprayed`)
- sprayed/green: (`number_of_rooms == number_sprayed`)

Are you able to fill in the blanks for this?

**Comment by sbabur** [comment]
@onlyjsmith I didn't think we had a blue color coding for Botswana, I thought it was just green/red/yellow?

For Namibia it would be:
Not sprayed:  numbersprayed_ddt == 0 AND numbersprayed_delta == 0
Partially sprayed: 0 < numbersprayed_ddt +numbersprayed_delta < number_sprayable
Fully sprayed: number_sprayable = numbersprayed_ddt +numbersprayed_delta

**Comment by onlyjsmith** [comment]
@sbabur thanks. we think we've been able to implement this, and it's deployed already on staging version `v1.0.8-16-g69ab6b7`

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith Working as expected - ok to close
