### ISSUE TITLE
Include separate user analytics page for each country instance

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#2]
First task is to review Google Analytics configuration, see if possible to create a filtered page for each instance (Nam, Bwa, etc), and invite specified users to _only_ see their instance's analytics. 

If not, will need to look for other solutions.

**Comment by TNgidi** [comment]
These were taken from a table sent by Sameen

**System Crash Rate** -->  How often the system experiences an unexpected exit
**System latency** -->  Round trip time from request to a response
**Data Sync Frequency** --> Time between data entry and data sync
**GPS Accuracy** --> Accuracy measure of collected GPS Points
**Monthly or daily active user** --> Number of unique users on a given day or month (aggregated)
**Geographic distribution** --> Geography of where the system is used.
**Session length** --> Time between opening and closing the system
**Session interval** --> Length of time between user’s first session and their next one.
**Error rates** --> How often users encounter an error
**Reporting time** --> Average length of time to complete data entry
**Data usage** -->  How much data is required for each user
**Reporting Lag** --> Time between initial event and entry into the system

**Comment by onlyjsmith** [comment]
We've set up the filtered views for NAM and BWA. We are testing over the next couple of days to check that the right analytics events are coming through to the view - will update in here our results. Please note that the filters apparently take 24 hours to apply (no idea why), so this process might well take a few days... Also, this is linked to redeployment of production version (to update the Google Analytics account number)

Next step will be to invite _testing_ users to each view: @sbabur can you give us a short list of users and an associated Google email address that you want to add to an instance's analytics view. This can be just you in the first instance. We will add others once we're certain it works.

**Comment by onlyjsmith** [comment]
Currently waiting - for redeployment of production version with updated UA

**Comment by onlyjsmith** [comment]
Confirm the filtering approach looks like it can work. 

Waiting to redeploy production version

**Comment by onlyjsmith** [comment]
Filtered views created for all 5 instances (Bwa, Nam, Swz, Zwe-Mats, Zwe-Matn) on both staging and production. Have added @sbabur as viewer for all of them.

**Comment by sbabur** [comment]
@onlyjsmith - looks good, can close issue
