### ISSUE TITLE
add name to Plan

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#20]
Currently when you edit an existing Plan, the 'name' of the plan is the old timestamp. You'd expect to have the timestamp update, but it stays the same.

**Comment by onlyjsmith** [comment]
@sbabur We're reviewing the code for some changes here. Will update here.

**Comment by sbabur** [comment]
@onlyjsmith Let's put this off until after microplanning then - I'm creating training materials right now and then am traveling so I won't have enough time to test/update training materials before the team starts using it

**Comment by onlyjsmith** [comment]
@sbabur This was on the 'nice-to-have' for this week, but we can delay it. 

Just to note, as with issue #21, sometimes the code is already merged in for use with other features, and we can't hold back an individual feature. We can always fix bugs with it, and in extreme cases we might be able to disable it. Hope this makes sense!

**Comment by sbabur** [comment]
@onlyjsmith Validated - can close
