### ISSUE TITLE
season filtering exclusive/inclusive

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#21]
Need to confirm we're doing the filtering correctly for both:
- [ ] e.g. if to _today_, needs to be `<=` today's date
- [ ] season-selector

**Comment by onlyjsmith** [comment]
@sbabur gave this example: she added a single record on April 24, set the filter and could still see the single record

![img_25042018_132905_0](https://user-images.githubusercontent.com/148280/39229787-59e1c478-4864-11e8-8041-c31206fc9650.png)

**Comment by onlyjsmith** [comment]
@sbabur filtering fixed. released on staging as version `v1.0.8-18-g569af00`

**Comment by sbabur** [comment]
@onlyjsmith Working correctly when I test - we can close this.

**Comment by sbabur** [comment]
@onlyjsmith Just tested Namibia Staging and I am seeing the same issue actually - 

![image](https://user-images.githubusercontent.com/37877007/39427910-c065ba7a-4caf-11e8-946b-6470cd30408f.png)

**Comment by onlyjsmith** [comment]
Can you confirm the version number you’re using for Namibia? Is in sidebar.

**Comment by sbabur** [comment]
@onlyjsmith Seasons selection seems to be ok, just an issue when custom dates are used. Version Version v1.0.10-1-g03f76b3:

Seasons:
![image](https://user-images.githubusercontent.com/37877007/39460802-80e6bae4-4d30-11e8-92ae-74e950684417.png)


Custom Dates:
![image](https://user-images.githubusercontent.com/37877007/39460783-6f8e9172-4d30-11e8-8c0c-f231cb9f31a0.png)

**Comment by onlyjsmith** [comment]
Thanks - we'll investigate

**Comment by onlyjsmith** [comment]
Ok, I've seen where this is going wrong. We've actually already fixed this, but not deployed the fix yet. We'll either extract the fix from the larger piece of work, or will make the change separately - either way we'll deploy this week,

**Comment by onlyjsmith** [comment]
@sbabur Fix is deployed on staging. Ok to close?

**Comment by sbabur** [comment]
@onlyjsmith Ok to close, can deploy to PROD after Namibia microplanning is done

**Comment by onlyjsmith** [comment]
@sbabur Afraid this is already merged into two of the other fixes in the next release (removing District filter for BWA, and restricting adding duplicate seasons), so can't delay releasing this one, without not doing any of the other fixes.
