### ISSUE TITLE
Clean up PROD plans

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#27]
With the new approach for creating season Plans, there are a lot of legacy plans in the system due to the sequential updates that were made since users hit 'Save' a number of times last year.

Can we clean these up? Only the most recent plan is the real 2017/2018 plan. 

Going forward with the new approach, they will continue to update the single annual plan, rather than creating sequential plans in increments.

Applies to Bwa and Nam instances.

**Comment by sbabur** [comment]
@onlyjsmith Example from Namibia - only most **recent** plan is the real one, rest are all drafts

![image](https://user-images.githubusercontent.com/37877007/39422634-736466de-4c98-11e8-981c-4b384e834583.png)

**Comment by onlyjsmith** [comment]
Yes - we can sort this out. Will do this week and update you

**Comment by onlyjsmith** [comment]
Update:
- [x] kept the plans from `production` for NAM, BWA, ZWE-MATS, ZWE-MATN, SWZ
- [x] all the other plans on `staging` and `production` are deleted

Rationale:
- there should be only one plan for each of the `production` instances, and we should expect `staging` to be deleted or wiped at any point

Can discuss on call today

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith Yup - ok to close. I'll open up another support item to clean up the 2018/2019 Namibia plan so we have a single National plan (I think it will just be a matter of deleting the ones the team added this week and uploading the one Katelyn and I give you)...as a heads up

**Comment by onlyjsmith** [comment]
Thanks - sounds good. Let us know when the planning is done, and we can
also take a look at what's been created.
