### ISSUE TITLE
New records not showing up in Namibia Dashboard, Syncing issue? 

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#28]
Including a video as I'm not really sure what the issue is here

I submitted 2 records for Namibia Stage. From Monitor Season options Oct 2017 and Dec 2018, I selected Oct 2017. However the records I submitted on April 30th are not showing up in Monitor when October 2017 is selected, and I don't see any place where the filters would be impacting this. I also removed all filters and re-loaded the responses but the responses only go up for April 26th. 

https://www.useloom.com/share/96a9fcca31704ae18d75213f2ea3c52d?focus_title=1&muted=1

**Comment by sbabur** [comment]
![image](https://user-images.githubusercontent.com/37877007/39428397-6a6c0122-4cb1-11e8-9d3e-16b867c53f03.png)

**Comment by onlyjsmith** [comment]
thanks @sbabur - definitely shouldn't be happening. we're looking at now.

**Comment by onlyjsmith** [comment]
@sbabur can you retry, but this time try clicking the "Include responses outside plan" checkbox at the bottom of the filters. We think there may not be a problem with syncing, but with the fact that we default to only showing responses that are within the plan.

<img width="466" alt="screenshot 2018-05-02 10 10 46 https nam app-stage disarm io irs monitor" src="https://user-images.githubusercontent.com/148280/39512545-a5c50084-4df1-11e8-852f-8d7ce3fe5270.png">

**Comment by sbabur** [comment]
@onlyjsmith Yup, that was the issue. All is well and we can close this. Training tip :)
