### ISSUE TITLE
Update NAM geodata

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#29]
Expecting updated data on Weds/Thurs. Aiming to have deployed for use in-country on Monday 7 May.

cc/ @sbabur

**Comment by HughSt** [comment]
Taking a look today at the latest data being collected from the field, will update asap.

**Comment by onlyjsmith** [comment]
@sbabur Namibia villages updated on _staging_ with the attached file
[nam.villages.20180502.json.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/1967669/nam.villages.20180502.json.zip)

I've checked and it looks changed on staging. If you confirm you're happy I'll update on production too.

**Comment by sbabur** [comment]
@onlyjsmith Katelyn did some spot checking and gives her seal of approval - this can be updated on production

**Comment by onlyjsmith** [comment]
@sbabur thanks. Updated on Production too

**Comment by sbabur** [comment]
@onlyjsmith can close
