### ISSUE TITLE
Record relevant data collection timestamps

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#3]
From Sameen:

> Mostly interested in being able to see:
> 1. How long it takes to fill out a form (currently record form start timestamp, so just need completion timestamp)
> 2. Lag between form completion and syncing

**Comment by onlyjsmith** [comment]
Have located places in code to insert timestamps.

1. We think the 'form-filling duration' measure might not make much sense if the form is edited: we're not using any in-page timers for activity yet. However, for simple 'open-form-and-complete' workflows it should work fine. Suggest only recording the time for the first form completion event, not any edits. (Could possibly also record the number of edits - will see if is possible - could then ignore any forms with edits when you're calculating an average duration to complete a form)
2. Lag between form completion and syncing should be possible to calculate and give a useful value.

**Comment by onlyjsmith** [comment]
@sbabur can you review this one too - is just an extract - have cut out any columns not related to timestamps

[nam_responses_2018-04-10_1241.xlsx](https://github.com/disarm-platform/user-requests-and-feedback/files/1894242/nam_responses_2018-04-10_1241.xlsx)

**Comment by sbabur** [comment]
@onlyjsmith can you confirm/clarify my understanding of the different columns:


recorded_on | Form start   time?
initial_form_completion_duration_seconds |  Clear to me
most_recent_form_completed_time | Last time they hit Save?
form_sync_lag_minutes | Difference between last time they hit 'Save/Completion' and sync?
updated_at | Only recorded if a form is edited?

**Comment by onlyjsmith** [comment]
1. `recorded_on` - when a user opens a new form
2. `initial_form_completion_duration_seconds` - lag between form being created and first time it's saved (not affected by subsequent edits)
3. `most_recent_form_completed_time` - the last time user clicks save
4. `form_sync_lag_minutes` - time between last save and successful sync
5. `updated_at` - I don’t think we control that, it might come from the DB

Before closing this we will:
- [ ] confirm #3 - we might be able to improve where it’s being set
- [ ] confirm where `updated_at` comes from

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith ok to close

**Comment by sbabur** [comment]
@onlyjsmith Hi Jonathan,

I’m not seeing a timestamp for the when Namibia forms were actually synced. Am I looking in the wrong place or did this disappear?  

I only see the following:
recorded_on
initial_form_completion_duration_seconds
most_recent_form_completed_time
updated_at

**Comment by onlyjsmith** [comment]
hi @sbabur, thanks for reporting. we’ll take a look. I don’t think we’ve removed any fields.

**Comment by onlyjsmith** [comment]
i've opened a new issue at https://github.com/disarm-platform/user-requests-and-feedback/issues/104

**Comment by sbabur** [comment]
Thanks Jonathan.

Please no updates without discussing first!
