### ISSUE TITLE
User permissions error with Admin - Season write

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#30]
@onlyjsmith 
I am getting the below errors when I update seasons, however the permissions are set correctly:

![image](https://user-images.githubusercontent.com/37877007/39565054-babad014-4ee0-11e8-9c41-511b4f5055fe.png)

![image](https://user-images.githubusercontent.com/37877007/39565062-bf80c1d0-4ee0-11e8-9ca1-1eff8e820606.png)

**Comment by onlyjsmith** [comment]
@sbabur ok to close? This should be closed by changes noted on #33

**Comment by sbabur** [comment]
@onlyjsmith Can close
