### ISSUE TITLE
Issue with Admin- Seasons read

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#31]
User with read-only seasons privilege cannot access page

https://www.useloom.com/share/cc770ef14738402db9e917963a0eb13c

**Comment by onlyjsmith** [comment]
Can you try again for this and #30?

I think there was a missing `config` permission that's also required. 

We will be significantly improving the users management as part of our next phase.

**Comment by onlyjsmith** [comment]
@sbabur ok to close? This should be closed by changes noted on #33

**Comment by sbabur** [comment]
Validated - can close
