### ISSUE TITLE
Changing permissions forces all users to log out - re-add

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#32]
@onlyjsmith 

https://www.useloom.com/share/91ff1d6063d84bb4b0195ffa1ee174c9 

Not offline
Botwana syncs just fine
Namibia is not syncing

**Comment by sbabur** [comment]
@onlyjsmith It worked after I just logged out and logged back in. 

I did just add a new user to the Namibia instance a few minutes ago - could this be the same issue where changes to the user list require all users to log out and then log back in?

**Comment by sbabur** [comment]
@onlyjsmith I just made another change to the permissions and got a 'current API key' not valid error, so I think this is where the issue is

**Comment by onlyjsmith** [comment]
@sbabur thanks. Users who've had their permissions changed will need to, but everyone else will have no issues. The original bug we opened on this was more of a 'check this', than an actual bug. 

So the issue you're reporting is likely to be something else. I'll close this, and open a new issue.
