### ISSUE TITLE
User Authentication changes not working

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#33]
@onlyjsmith 

I modified user nam2 - after 1 hour updated username is still not found by system

![image](https://user-images.githubusercontent.com/37877007/39614267-cc25ae9c-4f98-11e8-85fd-b8f15f8ccc07.png)

I created user nam 32- after 1.5 hours the user is still not found by the system

![image](https://user-images.githubusercontent.com/37877007/39614262-c11688d2-4f98-11e8-8268-261f218898f0.png)

**Comment by onlyjsmith** [comment]
@sbabur We've changed the way the sheets updates the users. It will be more reliable in response to edits to the sheet. It should take between 10-20 mins for changes to propagate, but could be much shorter, just a few minutes. This will be improved as part of the upgraded user editing flow.

Can you confirm that the user-changes you made are currently working, and that any other changes are visible within ~20 mins?

**Comment by sbabur** [comment]
@onlyjsmith new users are able to log in, but Seasons + Config doesn't seem to be working

https://www.useloom.com/share/24362a6eef7e4d02911fdd788f493283

**Comment by onlyjsmith** [comment]
We can reproduce. Working on fix.

**Comment by sbabur** [comment]
@onlyjsmith - no problems encountered/reported on this - can close
