### ISSUE TITLE
Problem syncing from record

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#34]
useloom.com/share/91ff1d6063d84bb4b0195ffa1ee174c9

Not offline
Botwana syncs just fine
Namibia is not syncing

Related to #32

**Comment by onlyjsmith** [comment]
@sbabur opened this, and investigating.

**Comment by onlyjsmith** [comment]
This is due to the permissions change. There are actually two messages that pop up, but the one saying 'logout and login again' is hidden by the first. We'll change the notification to make it clearer.

**Comment by onlyjsmith** [comment]
@sbabur we've done this on staging, but won't release to master until next release (which we can hold until after training)

**Comment by sbabur** [comment]
@onlyjsmith I think all is well on this now - has the updated/clearer notification been released to production?

**Comment by TNgidi** [comment]
Yes, it is already released. Happy to close?

**Comment by sbabur** [comment]
@TNgidi Tested and this is working, can close, thank you
