### ISSUE TITLE
Namibia village selections - ensure unselectable villages are clipped

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#35]
I think there were only a handful of villages that truly could not be selected despite trying all overlapping districts from the dropdown selection, but can you confirm that the problematic ones are clipped as needed? 

Also, some intermittent issue with the polygon multi-village selector:  

https://www.useloom.com/share/c287e29832a74c6185d0181831577554

**Comment by onlyjsmith** [comment]
@sbabur noted - taking a look.

**Comment by onlyjsmith** [comment]
@sbabur think this is closed

**Comment by onlyjsmith** [comment]
@sbabur Sorry, not this issue. We're still looking at this.

**Comment by onlyjsmith** [comment]
There shouldn’t be any villages that are not selectable now. Can you check you’re on the latest version (v1.0.12). We’ve tried on a few different machines and cannot reproduce.

**Comment by sbabur** [comment]
@onlyjsmith We think this is working 100% now - can close

**Comment by sbabur** [comment]
@onlyjsmith We can close this - selection for Namibia is working per all of our tests. If something does come up again, we can re-open.

**Comment by onlyjsmith** [comment]
Ok - thanks.
