### ISSUE TITLE
Botswana Polygon Selection Issue - 2 villages selected with 1 click, mismatch between Campaign Summary count and Plan count

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#38]
@onlyjsmith 

https://www.useloom.com/share/5210a8c496144c9c9a53411d6dce687a

Tried to select 1 polygon, 2 were selected
Campaign Summary reflects 10 villages
Plan Output table reflects 11 villages
Plan Load reflects 11 villages

**Comment by onlyjsmith** [comment]
@sbabur Thanks. We can confirm. 

There may have been a new field added in the updated data called ‘unique_ID’. We didn’t change any config to match, so it’s using the original id field, which contains duplicates. 

What is the timing for a fix to this? We could do with thinking this through properly before figuring the best way to fix.

**Comment by sbabur** [comment]
@onlyjsmith Not urgent, we are aiming to do a bunch of testing over the next 2 weeks to try and uncover any lingering bugs, and would like all bug fixes to be made by June 8th in time for program field-testing - we can discuss timelines more on our call.

**Comment by onlyjsmith** [comment]
Sounds good. We will want to have a fix working and tested before June.

**Comment by onlyjsmith** [comment]
This worth discussing tomorrow. 

We’ve nearly finalised the plan for longer-term fixing of this. It will relate to the concept of ‘packaging’ up a Plan, some Responses and some Geodata into a ‘Season’, or something similar.

Mostly it has implications for ‘backwards compatibility’ - for example, the geodata is now updated and uses a different field to identify areas, let’s call it “new_field”. Last year’s Plan and Responses and aggregations config all use “old_field”. That means that with the updated geodata, it won’t be possible to reliably spatially aggregate the Responses.

**Comment by onlyjsmith** [comment]
@sbabur think this one is closed, waiting instead for #39 for a more comprehensive update of data. We’ll try to make sure our geodata validation is working by then, to make updating geodata a simpler process.

**Comment by sbabur** [comment]
@onlyjsmith Yes, ok to close
