### ISSUE TITLE
Increase text/object size on data collection forms

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#4]
Critical for use on tablets. At the moment, the text and buttons are often too small, and hard to use, especially in the field (direct sun, moving about, etc).

We previously tried to fix quickly, and were able to change sizes of everything _except_ the forms. As the forms are rendered separately by `knockout`, we're going to need a different approach.

**Comment by onlyjsmith** [comment]
@sbabur we think we've got a working solution for this. trying out and will let you have a look on a deployed staging version when it's up, aiming for early next week.

**Comment by onlyjsmith** [comment]
@sbabur this is on staging - ok to close?

**Comment by sbabur** [comment]
@onlyjsmith ok to close
