### ISSUE TITLE
Monitor should only show admin units in Plan

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#42]
The map and summary tables should only show the admin units in the Plan that is loaded - this make interpreting the dashboard very difficult as you see a sea of red on the map, and a coverage table full of 0's and you would simply have to remember what was in the plan and what wasn't.

https://www.useloom.com/share/56988014497346ad88dc1315d4d96f7f

**Comment by onlyjsmith** [comment]
Thanks @sbabur, we’ll take a look. Can you check if you’ve got the ‘show responses outside plan’ checkbox turned on - it’s on the ‘advanced’ tab.

**Comment by sbabur** [comment]
@onlyjsmith Behavior is the same regardless of whether box is checked or unchecked:

https://www.useloom.com/share/4a13b759a9a84c6c8634474385f13269 

With the box checked, we would expect to see the GPS coordinates on the map, but don't expect to see them included in the aggregation calculations, and don't expect to see non-plan admin units appear in either the map or summary table.

**Comment by onlyjsmith** [comment]
Thanks for checking. We’re working on the issue.

**Comment by onlyjsmith** [comment]
We’ve implemented a fix  - should be released on staging tomorrow to test.

**Comment by onlyjsmith** [comment]
Released in v1.2.0
