### ISSUE TITLE
Can we remove clusters from BWA configuration

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#43]
I don't think they're used anywhere, but the current configuration requires users to download them.

**Comment by onlyjsmith** [comment]
@sbabur can you confirm if they’re still required?

**Comment by sbabur** [comment]
@onlyjsmith Why would you want to remove these? Is this a size issue?

**Comment by onlyjsmith** [comment]
Yes - only that. Is fine to leave them in. They were removed from other instances, so thought I’d check.

**Comment by onlyjsmith** [comment]
@sbabur fine to close?

**Comment by sbabur** [comment]
@onlyjsmith Yes, ok to close. Let's keep them in, we weren't facing any problems downloading/having them.
