### ISSUE TITLE
Changing season in one instance impacts seasons in all instances

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#44]
I added a new season in instance ID tilipimi-8

After saving, the new season was also reflecting in the production instance

https://www.useloom.com/share/9848aa2c9aec4c37b6a6ebd295a48c17

**Comment by onlyjsmith** [comment]
That’s currently the expected behaviour. The season start_dates are written directly onto the configuration that’s used for all instances. We’re looking at ways to improve as we go forward, but currently we only have one configuration for a country, which is used across all the instance_ids.

**Comment by sbabur** [comment]
@onlyjsmith Noted - can close
