### ISSUE TITLE
Encountering 'Error: Plan not valid' when attempting to view last year's IRS data on Monitor

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#45]
Using the production instance:

https://www.useloom.com/share/b883ebd1c8aa4a5da109e3f5aed8e8ec

**Comment by onlyjsmith** [comment]
Thanks - taking a look.

**Comment by onlyjsmith** [comment]
Plans now _must_ have a name. We’ll see if we can update all last year’s plans to have one - will be ‘Unnamed’ or similar, but will stop them breaking the current application.

**Comment by sbabur** [comment]
@onlyjsmith Can you just name them '2017 IRS Plan' ?

**Comment by onlyjsmith** [comment]
Sure - we’ll rename them to that tomorrow.

**Comment by onlyjsmith** [comment]
We've renamed the plans without names to ‘2017 IRS Plan'

**Comment by sbabur** [comment]
Validated - can close
