### ISSUE TITLE
Too easy to save multiple plans w/ same name

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#47]
Upon clicking the Create button, I've noticed the system sometimes quietly registers 2-3 plans depending on how the user clicks (its really easy to accidentally to this). Similar to seasons, can we make sure Plan names are not identical with message 'Plan with this name already created'

![image](https://user-images.githubusercontent.com/37877007/40230102-b7f5a1a8-5a96-11e8-81e2-75181bf8b1aa.png)

**Comment by onlyjsmith** [comment]
We’ve implemented a fix - should be released on staging tomorrow to test.

**Comment by onlyjsmith** [comment]
@sbabur Already released - happy to close?

**Comment by sbabur** [comment]
@onlyjsmith Yes, can close.
