### ISSUE TITLE
Map zooms out when selecting villages on Plan

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#48]
@onlyjsmith Overall I've noticed huge improvements in the tool here. It used to do this a lot but this is the first time I've encountered it in the last week while seeing up a bunch of test plans:

https://www.useloom.com/share/fd3c1041bc7e4ac7934458a6849e09cc?focus_title=1&muted=1

**Comment by onlyjsmith** [comment]
fixed in v1.2.1

**Comment by sbabur** [comment]
@onlyjsmith Done a bit of testing, can close and will keep an eye out in case it comes up again
