### ISSUE TITLE
Application freezes when custom location option used (bwa and nam)

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#50]
@onlyjsmith 

Reported by Katelyn on nam, production, instance ID hudiyipu-307, Samsung phone

Replicated by Sameen on nam, production, instance ID hudiyipu-307, Lenovo Thinkpad
Replicated by Sameen on bwa, production as well

https://www.useloom.com/share/5a6dff6b0568435fa6fd65e45ce68027?focus_title=1&muted=1

**Comment by TNgidi** [comment]
Thanks, we are investigating.

**Comment by onlyjsmith** [comment]
hotfixed in v1.2.2

**Comment by sbabur** [comment]
@onlyjsmith Validated, can close
