### ISSUE TITLE
[monitor] hotfix: missing error message if responses request fails

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#51]
At the moment, if the network request for Responses fails, there's no notification to user, and the buttons to retrying are disabled.

We've written and tested the hotfix, aiming to deploy tomorrow, and will notify you.

cc @sbabur

**Comment by onlyjsmith** [comment]
@sbabur have merged and deployed as hotfix, currently on v1.2.5

**Comment by sbabur** [comment]
Validated - can close
