### ISSUE TITLE
Missing 'Add to Homescreen' option on mobile

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#52]
@onlyjsmith Did some research online to see if I was missing some setting, but it appears to be present for other websites - is this something you need to enable? The 'Open DiSARM' option does allow you to view in full screen as a 'Chrome app' but we are missing the shortcut we want to add on user's homescreen
 

![screenshot_2018-05-29-15-51-59](https://user-images.githubusercontent.com/37877007/40667450-7f6e360e-6362-11e8-9bc6-82eede8e7e8f.png)

![screenshot_2018-05-29-15-51-49](https://user-images.githubusercontent.com/37877007/40667453-802ddc52-6362-11e8-9866-06c0319cbfd3.png)

**Comment by TNgidi** [comment]
Thanks, investigating.

**Comment by onlyjsmith** [comment]
@sbabur I think DiSARM is already installed. See the menu says “Open in DiSARM”. I can reproduce this by having DiSARM already installed.

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi Thanks - you were right. I thought I had removed the app from my homescreen but I apparently had 2. I used to be able to add multiple but can no longer - is this a new chrome thing? Would have been nice to have TEST and PROD versions. Can close.
