### ISSUE TITLE
Plan module - unable to select villages on mobile device

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#53]
Plan works on desktop, but when testing on mobile, both myself (Samsung Tab E) and Katelyn (Motorola Droid Turbo2) found that tapping on villages elicited no response while in Edit mode

I could use the polygon tool, Katelyn reported not being able to (but I can have her check again)

**Comment by onlyjsmith** [comment]
This is known behaviour - we've not been expecting users to _do_ the planning on a mobile device, just to view the plan. We will investigate what's needed to activate touch behaviour on Plan, and will implement if it's quick.

**Comment by sbabur** [comment]
@onlyjsmith Thanks for clarifying, must have forgotten about this. I say we note this for longterm development, but let's not prioritize this for the 2018 irs season production version of the tool.  We can do the Botswana planning on laptops, and Namibia planning is already done. Programs will be field testing in a couple weeks and we can save ourselves the risk of pesky regression defects. 

Can close for now and I'll put it in the longer term requirements documentation?

**Comment by onlyjsmith** [comment]
Happy for you to note for longer-term dev. We’ve noted as an issue on our internal backlog, but won’t prioritise
