### ISSUE TITLE
Monitor - selected plan is not displaying in map, stuck on 1 plan

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#54]
@onlyjsmith Tested in Namibia, production (no test Instance ID) 

Was trying to test reviewing old season/plan data

![image](https://user-images.githubusercontent.com/37877007/40668532-0dc649b2-6365-11e8-9296-a2e4374f65a3.png)

**Comment by TNgidi** [comment]
Thanks we will investigate on this

**Comment by sbabur** [comment]
@TNgidi @onlyjsmith May be a related issue, but if you leave the dashboard and come back, the system remebers your Season selection but not your Plan selection

**Comment by onlyjsmith** [comment]
@sbabur have merged and deployed as hotfix, currently on v1.2.5

**Comment by onlyjsmith** [comment]
@sbabur confirmed we can close
