### ISSUE TITLE
Issue with type-to-filter functionality

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#55]
Two examples, both in V1.2.5

Bwa - live version
Nam - wixocaye-904

https://www.useloom.com/share/644767cfb1c246f4bb7ce3f14f313e7e 

https://www.useloom.com/share/74e229e155394af081a426cfb56ab87e

**Comment by TNgidi** [comment]
Thank you for reporting this bug, we are fixing it.

**Comment by onlyjsmith** [comment]
@sbabur There’s a fix on a special feature-testing branch here: https://deploy-preview-353--douma-app.netlify.com/#instance=nam 

With these ones, you can try a different country by change the `nam` at the end to `bwa`, etc.

Please take a look, and let us know if it’s better. @TNgidi is also testing for us. We can then include as a small hotfix today/tomorrow.

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi - This is working well, let's go ahead and use this fix. Also, with the botswana meetings being pushed, you can hold off and wrap this update in with others instead of a hotfix if that is more convenient for you

**Comment by TNgidi** [comment]
Great, we have deployed to staging, this will go in the next production release (we’ll let you know plan for this before we release).

**Comment by onlyjsmith** [comment]
This is merged into v1.2.10, currently deployed on production (and also staging)

**Comment by sbabur** [comment]
Validated - can close
