### ISSUE TITLE
Make Q11 (bed nets) in Namibia form numeric

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#56]
Minor form field item - this field is alphanumeric, not numeric. Mostly an issue as it impacts the type of keyboard that appears on mobile

**Comment by TNgidi** [comment]
We were able to reproduce this and we are working on a fix.

**Comment by TNgidi** [comment]
This has been fixed on the staging version and it works on my side. If you are happy we will copy to production.

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi Looks good - can deploy in next release

**Comment by onlyjsmith** [comment]
Copied to production, and confirmed working on production
