### ISSUE TITLE
Botswana Dashboard - Refusal reasons pie chart - missing Materials + Other reason

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#61]
@onlyjsmith 

Two categories are missing from the pie chart:

![image](https://user-images.githubusercontent.com/37877007/40903164-c8791634-67d6-11e8-81b9-c052d9c50044.png)

![image](https://user-images.githubusercontent.com/37877007/40903236-09e0d044-67d7-11e8-90c2-a6f60d850584.png)

**Comment by TNgidi** [comment]
We are investigating on this

**Comment by TNgidi** [comment]
We are not able to reproduce this, can I ask for your instance ID to try in on the number of records and plans you had?

**Comment by sbabur** [comment]
I tested this on Instance ID bikipusa-912, it could be because of the fake records, but even then the other categories appear at 0% so you would expect those 2 would as well.

**Comment by TNgidi** [comment]
Thanks, let me check on my side

**Comment by TNgidi** [comment]
Just to confirm I can reproduce the error now

**Comment by TNgidi** [comment]
@sbabur This was an issue with configuration not in the code and we are currently working on configuring it well for you. Sorry for the delay.

**Comment by TNgidi** [comment]
We have fixed this on the staging version and will copy to production if you are happy.

**Comment by sbabur** [comment]
@TNgidi @onlyjsmith Pie chart looks good, can close. Noticed that 'Other' category is missing in the summary table however. Will add a separate card for that.

**Comment by onlyjsmith** [comment]
Fixed. Deployed to prod + staging

**Comment by sbabur** [comment]
Validated - can close
