### ISSUE TITLE
[monitor] What does 'guess locations' do?

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#62]
From @sbabur:

>On Monitor, does the 'Guess Locations' checkbox try to put records into an admin unit based on gps, and if so does this mean the checkbox would allow those records to be counted in coverage calculations?

**Comment by onlyjsmith** [comment]
@sbabur, yes, that's the intention. We implemented it for some edge cases last year, but I think it's not still functioning... So I'd propose removing the checkbox at this point. If we find the need to match points with locations again, we can handle that separately again. 

This relates to #59 - i.e. see if we can make it easier for users to select the correct location.

**Comment by sbabur** [comment]
@onlyjsmith Noted, thanks for the clarification. Fine with keeping the checkbox unless we happen to have other updates being made to production. Getting close to field testing :)

**Comment by sbabur** [comment]
@onlyjsmith We still DO want to keep the 'Show Responses Outside of Plan' checkbox though - want access to all the raw data via csv.

**Comment by onlyjsmith** [comment]
Closing - no further action needed on this.
