### ISSUE TITLE
Namibia bar chart does not respond to filter

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#65]
@onlyjsmith @TNgidi Districts will want to be able to monitor their own rooms sprayed vs. not sprayed over time counts, they don't care about national.

If you need to prioritize: The Botswana issue (#64) is much higher priority given timelines. Namibia will not be field testing until mid-July, so fix by end of June is fine

**Comment by sbabur** [comment]
Nam production, v1.2.10, instance ID wixocaye-904

![screencapture-nam-app-disarm-io-irs-monitor-2018-06-20-10_08_07](https://user-images.githubusercontent.com/37877007/41645841-75e01956-7472-11e8-8adb-05a53497c118.png)

**Comment by TNgidi** [comment]
This has been fixed in version 1.2.12
