### ISSUE TITLE
Seasons changes not persisting + getting error

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#66]
Seasons changes not persisting while logged in as sameen.babur on test instance KASANE-TEST

Also getting a timeout error

https://www.useloom.com/share/1315f92f59d14ec592010420d41b98ea

**Comment by onlyjsmith** [comment]
Thanks, noted - we’ll take a look today.

**Comment by TNgidi** [comment]
@sbabur We have figured what the problem is and we are working on a fix for it. In the meantime if you have any changes you would like to implement on the seasons please lets know and we can implement them on our side for you.

**Comment by sbabur** [comment]
@TNgidi Great, thanks! No other changes for now

**Comment by sbabur** [comment]
@TNgidi @onlyjsmith Flagging this issue for field testing on Thursday. Let me know if this fix is feasible by EOD Tuesday latest, otherwise we will work around this during the group test activities.

**Comment by onlyjsmith** [comment]
Linked to #67.

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith Validated, ok to close
