### ISSUE TITLE
District filter not working

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#67]
@onlyjsmith @TNgidi 

Bwa production
Season: May 17 2017
Plan: Unnamed, 29 Areas (true 2017 IRS production plan from last year)

![image](https://user-images.githubusercontent.com/37877007/41895356-1df56318-7922-11e8-884c-14d0a6c5526e.png)

![image](https://user-images.githubusercontent.com/37877007/41897534-e48e7366-7927-11e8-964d-ffc31d166ba8.png)

![image](https://user-images.githubusercontent.com/37877007/41897546-ec3df2f8-7927-11e8-9b7a-11aad4e0f251.png)

**Comment by sbabur** [comment]
I wonder if this is a case sensitivity issue, but it is weird because it was working on Friday on this same version!

**Comment by sbabur** [comment]
From the Training Guide, took this screenshot on Friday:

![image](https://user-images.githubusercontent.com/37877007/41898076-4ff61248-7929-11e8-9d7c-dd94553b148a.png)

**Comment by onlyjsmith** [comment]
Linked to #66. We’re finalising the fix for both today.

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi validated, can close
