### ISSUE TITLE
finalise custom location selection

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#69]
1. Keep the 2 (area and subarea) dropdowns
2. Have Confirmation popup for custom location checkbox
3. Autocomplete the custom text box.

**Comment by onlyjsmith** [comment]
@sbabur We've implemented 1 & 2 above, but I don't 3 is the right thing to do.

It starts to get too complex from a UX perspective - you can get 4-5 clicks/steps into one process without having finished entering the info. 

If a user can't find the location in the dropdowns, but they've found the checkbox, _and_ clicked the confirmation, then let's allow them to enter they text they want. They're already off the main 'path', and if we frustrate them at this point (e.g. by making them find a setting at the bottom of a list, etc), we've got ourselves some unhappy users!

**Comment by sbabur** [comment]
@onlyjsmith I would rather we do 1 and 3.

This is really important for Namibia - users simply do not always know what the right answer for dropdown 1 is, even if they know what they want to enter for dropdown 2.  We will end up with a lot of in-plan responses with typed-in locations that make the dashboard a lot less useful. 

We will train the way we need to, but please implement 1 and 3.  Cannot stress enough hard 1 and 2 will make dashboard analysis in Namibia.

**Comment by onlyjsmith** [comment]
Ok, let's talk through on the call tomorrow. We'll be able to find the right solution! We definitely want to avoid typed-in answers.

We've worked on solutions for all the parts, it's just the combination of them that is proving tricky. To keep it simple to use and maintain, I'd like to stick to one page of drop-downs, with as little magic or logic as possible. And we'll need to find one approach that works well for both BWA and NAM.

**Comment by onlyjsmith** [comment]
@sbabur We've got an updated version currently deployed to staging, which looks like it can handle 1 + 2 + 3. Take a look if you have a chance before the call, and we can discuss later.

**Comment by onlyjsmith** [comment]
@sbabur we’re waiting for confirmation from Katelyn/Erica that this approach works before we release onto master - is that correct?

**Comment by sbabur** [comment]
@onlyjsmith Correct - will confirm ASAP

**Comment by sbabur** [comment]
@onlyjsmith Confirmed - let's go with the current approach that is in staging.

Quick note to correct the constituency spelling mistake in Namibia

![image](https://user-images.githubusercontent.com/37877007/42366248-fcf2591e-8100-11e8-8706-540508ce0215.png)

Let's package this update with the other items you are working on rather than having multiple releases, however. Can wait until early/mid next week to have this in prod

**Comment by TNgidi** [comment]
@sbabur, please let us know if its ok to close this one

**Comment by sbabur** [comment]
Validated, can close
