### ISSUE TITLE
Update BWA geodata to include all districts

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#7]

**Comment by onlyjsmith** [comment]
@sbabur also notes 

> there is a good chance the org unit boundaries/structure counts will be refined after discussions with the program, 

We'll need to think about how best to handle this, whether we have time to put in place any options for programmes to update their own geodata.

**Comment by onlyjsmith** [comment]
Hi @sbabur - when can we expect to have the first updated version of this data?

**Comment by sbabur** [comment]
@onlyjsmith Hi Jonathan - I'm sending you the village and district shapefiles via email due to size/format. Please take a look and let me know if there are any issues.

Note that there are some ground validation activities occurring which may result in village refinements. Also, structure counts may be refined during trainings.

**Comment by sbabur** [comment]
@onlyjsmith Nevermind - attaching here 

[Admin_Districts_usedbyNMP.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/1898727/Admin_Districts_usedbyNMP.zip)
[Villages (operational unit).zip](https://github.com/disarm-platform/user-requests-and-feedback/files/1898728/Villages.operational.unit.zip)

**Comment by onlyjsmith** [comment]
Thanks - will take a look today

**Comment by mosaic141688** [comment]
@sbabur and @HughSt  The bwa villages seem to be missing `Num_Rooms` (Number of rooms). 
Can you remember where we this information came from last year?

**Comment by sbabur** [comment]
Briefly:
1.	HOT ground-truthing/validation exercises are expected to modify the village boundaries and enumeration counts
2.	The final num_rooms count would ideally be an extension of Hugh’s model
3.	The final structure will be consistent – the only changes would be the exact boundaries and num_rooms integer
a.	Can we use placeholders at the moment for testing purposes, with the understanding that updates will need to be made to the content but not the structure of the files?

We can discuss more on our call if needed, but this would essentially be planning for a couple days around the HOT validations/trainings for some refinements, as was the case last year. If the import method is substantially improved and doesn’t need to be as hands-on, great. Regardless, a heads up to plan for this.

**Comment by onlyjsmith** [comment]
@HughSt please note that @sbabur wants to rerun your model from last year, based on some updated ground-truth data from HOT

**Comment by HughSt** [comment]
Sorry - I need to sort out notifications so I don't miss these. I will update the new shapefile before Wed 25th with the correct numbers and will post here for visibility.

**Comment by HughSt** [comment]
@sbabur @onlyjsmith here is the updated village file for BWA. This includes NumStrct (estimated number of residential structures from OSM using the machine learning model) and Num_Rooms (estimated by modeling the relationship between median building size and mean number of rooms/building from observed data - provided by Katelyn last year). Please take a look and see whether this looks OK. Bear in mind that this assumes the latest (downloaded last week) OSM data is complete in the target areas. There are a few villages which have no OSM buildings in them.
[bwa.villages.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/1944981/bwa.villages.zip)

**Comment by HughSt** [comment]
Updated file attached without missing values for risk
[bwa.villages.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/1945407/bwa.villages.zip)

**Comment by HughSt** [comment]
Updated BWA village data with risk (with no missing values) and slightly updated Num_rooms estimate
[bwa.villages.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/1945481/bwa.villages.zip)

**Comment by onlyjsmith** [comment]
It looks like a lot of villages cross district boundaries in the 2018 updated geodata. As with Namibia last year (villages in multiple constituencies), this will cause problems with our current planning and aggregation approach. 

<img width="848" alt="screenshot 2018-04-26 12 33 36" src="https://user-images.githubusercontent.com/148280/39301035-1aa6ed02-494e-11e8-94b7-dc51f1d1ed5a.png">
<img width="1047" alt="screenshot 2018-04-26 12 34 24" src="https://user-images.githubusercontent.com/148280/39301064-318b34a6-494e-11e8-94d5-3987f8443b21.png">


We can look at changing the approach we take, but it will not be a 'quick fix'. @sbabur Can you confirm these are the real districts, whether there's another way we can group them. Meanwhile we will explore what would be required in the application.

@HughSt can you confirm how you extracted the `name_2` property (which refers to the District) for each village?

Related, it seems there's a parallel discussion about this on email - we should probably stick to one place, don't mind whether here or there.

cc @Nicolaidavies @mosaic141688 @TNgidi

**Comment by sbabur** [comment]
@onlyjsmith I discussed this with Ayo, and we are happy to get rid of the Planning district dropdown, and allow users to plan any area at once, without any district restrictions. Would that address the issue here? I recall with Namibia the problem was restricted to the selection of the polygon. 

Although the polygons overlap, each village is indeed only assigned to one district, so we should stick to that assignment in the form's cascading/filter dropdown as well as the dashboard aggregations.

**Comment by onlyjsmith** [comment]
@sbabur thanks for the reply, we've been working through the implications since the start of the week. Still going...

**Comment by onlyjsmith** [comment]
Works as follows:
- _Record_: the dropdown for location selection is based on the villages and which district they belong to
- _Aggregations_: depends on the district a village belongs to
- _Plan_: no district-level restriction on planning

**Comment by sbabur** [comment]
@onlyjsmith This matches the desired behavior - we can proceed

**Comment by onlyjsmith** [comment]
Need to ensure production and staging match, even if they're going to be updated #41 and #39

**Comment by onlyjsmith** [comment]
Staging and production currently match, config updated and geodata version number bumped. Closing again.
