### ISSUE TITLE
change Record list filtering

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#70]
1. Set in config a field from form
2. Change list record to include that field in-place of current `id` field.
2. Change list filter to use field

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi Validates, can close.

I suspect Namibia will want to filter either on Head of Household Name or Household Health Number, will scope of feedback when I am there week of 16th

**Comment by onlyjsmith** [comment]
Great - let us know and we can update the configuration to make it work. The requirements are that it needs to be a text field from the form.

**Comment by sbabur** [comment]
@onlyjsmith Quick question on the current config set up for this - does Namibia need to pick only one field to filter on, or is it possible to have multiple provided they are text fields?

Does text == alphanumeric? 

The 2 fields Namibia would be interested in filtering for are below, both alphanumeric. It would be nice to give users both options, but let me know if we need to pick one. No point trying to enhance this so we can pick 1 if that is the way you already set it up

![image](https://user-images.githubusercontent.com/37877007/42366463-91fec8a8-8101-11e8-984c-52677a811325.png)

**Comment by onlyjsmith** [comment]
Currently we can only handle a single field. Changing to handle multiple has a few implications that mean it’s not just a simple switch/fix. 

Alphanumeric or text input are both fine, so either the examples you give would work.
