### ISSUE TITLE
[form] BWA Add Q textfield for cattle posts

### ISSUE THREAD

**Issue by TNgidi** [disarm-platform/user-requests-and-feedback#71]

**Comment by onlyjsmith** [comment]
@sbabur Can you give us the exact wording they want for this question, where it should appear on the form, whether it is required or optional, and whether there are any pre-conditions required for it to show. 

Our suggestion, based on discussion we heard last week:
- "Record name of cattle post"
- text type
- on same page as "household head name", and underneath it
- not required
- no pre-conditions, and no later questions depend on it

**Comment by sbabur** [comment]
Hi Jonathan,

With 1 modification below, This seems find to me based on what we heard during the discussions, but forwarding to Erica for final confirmation during the Francistown meetings and not 100% sure yet if we are supposed to add it


  *   "Record cattle post or other place name"
  *   text type
  *   on same page as "household head name", and underneath it
  *   not required
  *   no pre-conditions, and no later questions depend on it

**Comment by onlyjsmith** [comment]
@sbabur Thanks - we'll wait until we hear confirmation from you before proceeding.

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi Got the go-ahead, will just be adding this one field

Final specs:
  *   "Record cattle post or other place name (if applicable)"
  *   text type
  *   on same page as "household head name", and underneath it
  *   not required
  *   no pre-conditions, and no later questions depend on it

**Comment by TNgidi** [comment]
@sbabur This has been done on staging and on production versions

**Comment by sbabur** [comment]
@TNgidi Validated, can close
