### ISSUE TITLE
Add Actellic to bwa and nam forms

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#74]
@onlyjsmith @TNgidi 

**Namibia**:
- Label: "How many structures were sprayed with Acetellic? (If 0, enter 0)"
- Input Type: Integer
- Mandatory: Yes
- Data validation: Remove all validations on this page and add a simple warning check to see if Delta + DDT + Actellic is <= to the total number of sprayable rooms

![image](https://user-images.githubusercontent.com/37877007/42207505-60174332-7eaa-11e8-9436-bbe6aa6ab740.png)

![image](https://user-images.githubusercontent.com/37877007/42208067-8fb02b94-7eab-11e8-9c58-6a4b34dbd0e3.png)

(While you are in there, can you remove the space between the ( and If and make the If capitalization consistent?)

**Botswana**:
- Label: "How many rooms in this homestead were sprayed with Actellic? (If none, enter 0)"
- Input Type: Integer
- Mandatory: Yes
- Data validation: Update rule shown to include Actellic

![image](https://user-images.githubusercontent.com/37877007/42207645-b6eaf37a-7eaa-11e8-98ac-8a64bb0bb984.png)

![image](https://user-images.githubusercontent.com/37877007/42207710-db73753c-7eaa-11e8-8431-069655a2e6ae.png)

**Comment by TNgidi** [comment]
This is done and it is live on both staging and production versions.

**Comment by TNgidi** [comment]
@sbabur please validate

**Comment by sbabur** [comment]
@TNgidi Can you fix the below cosmetic issue (i vs. I, and unnecessary space) and simplify the data validation rules?

Let's just have 1 data validation rule to check that DDT +Ddelta + Actellic = total number of rooms sprayed and remove the individual insecticide ones 

![image](https://user-images.githubusercontent.com/37877007/42443445-c27ddbb8-836d-11e8-8746-408fd6adc169.png)

![image](https://user-images.githubusercontent.com/37877007/42443366-91f4b930-836d-11e8-816a-b5e94bbc41cb.png)

**Comment by TNgidi** [comment]
I think we can close this as initial issue is finished and there is a new issue for the last comment: issue #79

**Comment by sbabur** [comment]
Yes, fine
