### ISSUE TITLE
Namibia Sub-Area dropdown does not get restricted to selected constituency 

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#76]
@onlyjsmith @TNgidi 

Namibia, v 1.2.13, instance ID NAMIBIA-TEST (set up for field testing activities)

Steps:
Select Area
Open Sub-Area dropdown and options are not restricted to selected Area
Selecting a Sub-Area from a different Area auto-correct the Area selection, but only on the first instance

Desired functionality:
Restrict options in Sub-Area to selected Area

https://www.useloom.com/share/1a1f1d50bc5d4c8ba0a7b944feeed000

**Comment by TNgidi** [comment]
@sbabur I was able to reproduce this error on my side

**Comment by TNgidi** [comment]
@sbabur Jonathan picked this up yesterday too and we have a fix for it.

**Comment by onlyjsmith** [comment]
Fixed by current dropdown setup.

**Comment by onlyjsmith** [comment]
@sbabur Fix is currently only on staging (see #69), but will be released to master once we get confirmation. Can close this one, to leave #69?

**Comment by sbabur** [comment]
@onlyjsmith Works for me, can close
