### ISSUE TITLE
BWA duplicate villages in 2017 Plan

### ISSUE THREAD

**Issue by TNgidi** [disarm-platform/user-requests-and-feedback#77]
We discovered a bug today on the Botswana instance which was caused by the erratic geodata from last year. If you recall we had villages with duplicate IDs, which made some calculations wrong. Today we discovered that on the dashboard the village NATA had the right calculations of percentage coverage even though it was showing 0 rooms found while also showing 1522 rooms sprayed and a coverage percentage of 41.9%. This was caused by duplicate village IDs in the 2017 Plan. We can’t tell these duplicates apart on the dashboard, so they’re only causing problems. 

The solution (which we’ve tested on production DB, as the only place that has this data) is to remove the duplicates from the Plan. This solves the problem (and probably some others too), but it looks like the Plan has shrunk from 29 to 27 areas! In reality the 2 which were removed were not showing as different areas on the dashboard, and were only causing problems like this. We have a backup of the original Plan, so can restore if we need to. 

Please let us know if you need more explanation, and if you want to revert the Plan to the 29. 

cc @sbabur

**Comment by sbabur** [comment]
@TNgidi Let's address this when Katelyn and Dominic come back to us with the new shapefile, which will not have duplicate ID's. That should revert things to 29 with proper unique IDs

**Comment by sbabur** [comment]
@TNgidi But can you send me a copy of the 29-village plan? We will sense-check

**Comment by onlyjsmith** [comment]
The downloaded geojson for the 2 versions of the Plan are identical. I downloaded the versions for the 27 and 29 villages and checked - there's no difference. I'm attaching a copy of the 29, but you'll see it contains only 27 villages - we've no way to tell them apart when we prepare the plan download.

[bwa_plan.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2167260/bwa_plan.zip)

**Comment by onlyjsmith** [comment]
And @sbabur I’ve updated the 2017 plan from ‘Unnamed’ to ‘2017 IRS Plan’. (DB edits like this are usually only possible if we’re already in the middle of any other fixes!)

**Comment by TNgidi** [comment]
This is okay to close, confirmed by @sbabur in an email
