### ISSUE TITLE
BWA Forms do not have validators for negative numbers on number of rooms sprayed

### ISSUE THREAD

**Issue by TNgidi** [disarm-platform/user-requests-and-feedback#78]
@sbabur While adding the textfield for Actellic we have discovered that the number fields do not check if the numbers are negative. DiSARM checks to ensure that they add up to the number of rooms sprayed. As shown in the screen bellow, in a homestead with 10 rooms this would pass because 15 + (-5) is 10. 
We can change to ensure it does not allow numbers less than 0. but we will not do anything without confirmition

![disarm botswana irs database 2018-07-06 10-48-40](https://user-images.githubusercontent.com/36029281/42369688-00f1183e-810b-11e8-9e52-5949933bb71c.png)

**Comment by sbabur** [comment]
@TNgidi Thanks! It would be great if you fixed this (all numeric values should be <= 0

We noticed this before but did not prioritize fixing it since its harder to do negative values on tablets, but agree that it is best to fix

**Comment by TNgidi** [comment]
The validations have been configured and they are ready for review on staging and production.

**Comment by TNgidi** [comment]
@sbabur please validate

**Comment by sbabur** [comment]
@TNgidi A couple more gaps:

![image](https://user-images.githubusercontent.com/37877007/42443009-96770090-836c-11e8-9bac-80c54d3e7a5e.png)

**Comment by sbabur** [comment]
![image](https://user-images.githubusercontent.com/37877007/42443218-2ef4da7c-836d-11e8-8a19-92386ef35da3.png)

**Comment by TNgidi** [comment]
#80

**Comment by TNgidi** [comment]
Opened issue #80 for the additional fields to be validated.

**Comment by TNgidi** [comment]
Think we can close this too, it was concerning the rooms sprayed with different chemicals (questions 17 and 18 on form), while now we have issue #80 for questions on number of people and rooms sprayed comparing traditional and modern.

**Comment by onlyjsmith** [comment]
@TNgidi sure
