### ISSUE TITLE
Redeploy staging and production

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#8]
- [x] staging
- [x] production

**Comment by onlyjsmith** [comment]
@sbabur we tried to redeploy for most of today - we've had to rebuild a server (been a while since we've deployed and things move on!) Should be able to get it working on Monday, and we'll send you a link

**Comment by onlyjsmith** [comment]
@sbabur aiming to have production (e.g. bwa.app.disarm.io) redeployed by early afternoon tomorrow.

**Comment by onlyjsmith** [comment]
@sbabur production is deployed as well (should see it as version `v1.0.8-8-g7c3106e`) e.g. at https://bwa.app.disarm.io

Please remember that without an `instance_id` set, this is the live production data. Feel free to use an instance_id to test it out.

There are two URLs for each which might be useful, e.g. for Namibia:
- https://nam.app.disarm.io/meta/logout - this forces a logout (but not cleaning of data) and is a neat way to try a new version
- https://nam.app.disarm.io/reset.html - if you're having trouble upgrading, visit this page and click the reset button then 'restart app'

**Comment by sbabur** [comment]
@onlyjsmith All looks good - can close
