### ISSUE TITLE
Add visit #/mop-up question to Namibia Form

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#83]
Exact questions TBD - can put in blocked for now

**Comment by TNgidi** [comment]
@sbabur What is the timeline for these three new cards: #83, #84, #85 ?
Any news on the exact wording of this one?

**Comment by sbabur** [comment]
Can these be done next week? Field testing this week so best to leave the instance alone until Monday.

Also getting feedback on the exact wording today


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by TNgidi** [comment]
@sbabur Yes, they can be done next week

**Comment by sbabur** [comment]
@TNgidi Shall we close this card and track with #86 ?

**Comment by TNgidi** [comment]
@sbabur We generally make an epic whereby, in our case, #86 would be a composed of a number of other cards so that we are able to track all aspects of transforming the form. Lets see what @onlyjsmith thinks.

**Comment by sbabur** [comment]
@TNgidi Validated in production, can close
