### ISSUE TITLE
NAM form transformation 

### ISSUE THREAD

**Issue by TNgidi** [disarm-platform/user-requests-and-feedback#86]
[DiSARM Form Design_Iitula and Joyce.xlsx](https://github.com/disarm-platform/user-requests-and-feedback/files/2210373/DiSARM.Form.Design_Iitula.and.Joyce.xlsx)
[Namibia Form Flow.pptx](https://github.com/disarm-platform/user-requests-and-feedback/files/2210374/Namibia.Form.Flow.pptx)

**Comment by sbabur** [comment]
@TNgidi Validated in production, can close
