### ISSUE TITLE
Allow NULL value for GPS coordinates for instances where Timeout Error cannot be resolved

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#88]
In instances where users are not able to collect GPS points due to hardware issues, they should still be able to submit their form details. These would count in coverage calculations according to their location dropdown selection, but would naturally not appear on the map.

**Comment by sbabur** [comment]
I'll give this one some thought over the weekend - perhaps we will focus on training to address this. The same problem would appear with other tools we have used in the field but I think because of training have not seen this be an actual issue implementation-wise. Plus those tablets would have sim cards, so would not have as much trouble as these sim-less tablets we were using?

**Comment by onlyjsmith** [comment]
Ok - thanks @sbabur. We’ve also started thinking through the implications. In principle I like the idea of making this configurable per-instance, but there are quite a few implications. Want to make sure we don’t interrupt the application too much. We’ll continue exploring our side, and can update next week.

**Comment by onlyjsmith** [comment]
Have made progress on approach. Aiming for staging this week.

**Comment by Nicolaidavies** [comment]
@onlyjsmith this was deployed on version `1.3.1`. Can we move to "Done"?

**Comment by sbabur** [comment]
@onlyjsmith Do you have a separate link I can test this out on?

**Comment by Nicolaidavies** [comment]
@sbabur Making gps or location selection optional requires a configuration change. 

Please let us know which instance you would like to test it on.

**Comment by sbabur** [comment]
@Nicolaidavies I can test anytime this week on Namibia Staging, or the week of the 20th.

**Comment by sbabur** [comment]
@Nicolaidavies sorry for the delay. I tested this again on  v1.3.1-4-geaa18d4  and while no validation issue pops up and the COMPLETE button is still enabled, I now get a 'could not save record locally' error

![screenshot_2018-08-10-08-27-35](https://user-images.githubusercontent.com/37877007/43942243-78798f6c-9c77-11e8-8b7d-d137060fb280.png)

**Comment by Nicolaidavies** [comment]
@sbabur Thank you for reporting it. We will take a look.

**Comment by TNgidi** [comment]
@sbabur and @Nicolaidavies I am able to reproduce this, I am going to open a new issue to easily track it

**Comment by TNgidi** [comment]
Working on the bug in issue #96
