### ISSUE TITLE
Dashboard User Authentication Issue

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#93]
@onlyjsmith @TNgidi I was working with bwa user 'myusername' that the following Read/Write Access:

Read: Plan, Monitor, Record
Write: Plan Monitor Record

After updating the permissions to the below I received a "User does not have sufficient permissions to access this endpoint."

Read: Monitor, Record
Write: Monitor Record

I then changed it to the below and received the same error (including in incognito mode)

Read: Plan, Monitor, Record
Write: Monitor Record

![image](https://user-images.githubusercontent.com/37877007/43316959-590cc1b2-919b-11e8-8543-a59f64a8ab6a.png)

![image](https://user-images.githubusercontent.com/37877007/43316968-5f8f3ede-919b-11e8-9b8e-30e2f854f88e.png)

**Comment by onlyjsmith** [comment]
cc @Nicolaidavies

**Comment by Nicolaidavies** [comment]
@sbabur Thanks for reporting this. 

I have added the permission `write:irs_plan` to the user `myusername` as a temporary solution until we fix the server.

**Comment by sbabur** [comment]
Thanks – assuming until this is fixed a user needs read/write access to plan to use the dashboard? Would write-only access suffice? Don’t mind using that as a workaround and tabling this for later… there are just some users who won’t have access to plan.

Sameen

**Comment by onlyjsmith** [comment]
Fix has been deployed on staging

**Comment by sbabur** [comment]
Want to be able to view Monitor without any plan Read or Write permission as long as there is Monitor permission, @onlyjsmith I think you said you would be adding a new card for that?

**Comment by Nicolaidavies** [comment]
@sbabur 

The current behaviour is: if a user has `irs_monitor:read` they can read all plans and all records without requiring further permissions. But this does not give them access to the `irs_plan` applet.

What is described in card #95 is already implemented.

**Comment by sbabur** [comment]
@Nicolaidavies Should I be testing in production?

**Comment by Nicolaidavies** [comment]
@sbabur it should work on both production and staging.

**Comment by sbabur** [comment]
@Nicolaidavies Tested on production and still seeing this issue (cleared cache, logged back in, on production instance, v1.3.1)

![image](https://user-images.githubusercontent.com/37877007/43642922-a6ec7272-9729-11e8-8ae1-a9eaed50c3fc.png)

![image](https://user-images.githubusercontent.com/37877007/43642924-aad35dec-9729-11e8-8433-6643b9312de1.png)

![image](https://user-images.githubusercontent.com/37877007/43642935-b2abe9e4-9729-11e8-8e95-2e140a23620d.png)

![image](https://user-images.githubusercontent.com/37877007/43642943-bc070690-9729-11e8-9169-bb37f24ab249.png)

**Comment by Nicolaidavies** [comment]
@sbabur 

I forgot to add a permission on the server. 

It should be fixed now.

**Comment by sbabur** [comment]
Thanks, this is working now and we can close this issue
