### ISSUE TITLE
Regression Bug - cannot load previous plan on dashboard

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#94]
https://www.useloom.com/share/2a5a6424068341308a91a349f8ae38c0?focus_title=1&muted=1 

Bwa production - v1.3.1, instance ID  quluguze-799

**Comment by TNgidi** [comment]
Thanks for reporting @sbabur, I am currently trying to reproduce this on my side

**Comment by TNgidi** [comment]
I was able to reproduce it on my side. Investigating further

**Comment by TNgidi** [comment]
@sbabur what was the expected behaviour in this case? We think it is working well by selecting the 22 areas and painting them with the selected layer.

**Comment by sbabur** [comment]
@TNgidi I think I was mistaken then, I was hitting Refresh after this video ends, and that is where it reverts back to the current plan - I think we can close this issue,

**Comment by TNgidi** [comment]
OK thanks, 
@onlyjsmith will close
