### ISSUE TITLE
change read:plan permission for dashboard

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#95]
Currently require a user to have `read` access to _Plan_, even though we only want them to have access to the _Dashboard_.

**Comment by Nicolaidavies** [comment]
@onlyjsmith Believe we can close this card. See https://github.com/disarm-platform/user-requests-and-feedback/issues/93#issuecomment-410175798

**Comment by onlyjsmith** [comment]
Already implemented - no action needed on this card
