### ISSUE TITLE
Change unsprayed question to numeric on Namibia form

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#97]
@TNgidi Hi - just noticed that this 1 field got left alphanumeric instead of numeric. Could you quickly change this today or tomorrow?

![screenshot_2018-08-10-09-24-15](https://user-images.githubusercontent.com/37877007/43944568-9efab816-9c7f-11e8-85f7-6155ab065d2f.png)

**Comment by TNgidi** [comment]
@sbabur Yes, we will change it and then inform you.

**Comment by TNgidi** [comment]
@sbabur We have changed this and it is on the  Config: nam@1.0.22 staging and production.

**Comment by sbabur** [comment]
@TNgidi Thank you! Validated and can close

**Comment by TNgidi** [comment]
Thanks, @onlyjsmith will close it
