### ISSUE TITLE
Update Botswana Form

### ISSUE THREAD

**Issue by sbabur** [disarm-platform/user-requests-and-feedback#99]
@onlyjsmith @TNgidi @Nicolaidavies I can make the form changes - can you add the existing json here?

Summary of changes:
- Update language
- Remove nets questions
- Do not ask enumeration questions on mop-up visits
- Add a question on unsprayable rooms and remove Unsprayable as a reason for not sprating

**Comment by Nicolaidavies** [comment]
Hi @sbabur 

Please find the current form attached.

[20180903.bwa.form.json.txt](https://github.com/disarm-platform/user-requests-and-feedback/files/2344923/20180903.bwa.form.json.txt)

**Comment by sbabur** [comment]
@TNgidi @Nicolaidavies I'm getting a 502 server error on survey js so I tried updating it in Notepad++ directly D:

Are you two having any luck with surveyjs?

Hopefully syntax error-free form attached. You can see that "n_rooms_material' is no longer an integer input as a refusal category, we now have a field called 'unsprayable' to capture the number of unsprayable rooms on the same page we capture total sprayable/modern sprayable/traditional sprayable room counts. The single dashboard summary table column for number of unsprayable rooms should just aggregate this field. 

[Botswana_Form_Sep042018.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2349531/Botswana_Form_Sep042018.zip)

**Comment by TNgidi** [comment]
Thanks for the form @sbabur it all works well, but I do not understand what you mean when you say "You can see that "n_rooms_material' is no longer an integer input as a refusal category". I tried to find the field "n_rooms_material" to understand more about it but I did not find it, did you completely remove it?

**Comment by sbabur** [comment]
Yes I completely removed that field. Instead of specifying at the end how many rooms were not sprayed due to being unsprayable, i removed that and added a separate new question in the page where we collect household room information.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by TNgidi** [comment]
Okay, I understand now. We will work on it and let you know to test

**Comment by sbabur** [comment]
@TNgidi Thanks Thokozani. Can you let me know when you are aiming to have these 3 changes ready for me test? Would by end of week be possible?

**Comment by TNgidi** [comment]
@sbabur It should be ready after lunch. @Nicolaidavies will be working on it around noon

**Comment by TNgidi** [comment]
@sbabur Please try again with surveyjs editor on your side, we have uncovered errors on the form you sent.

**Comment by sbabur** [comment]
See attached

[Botswana_Form_Sep062018.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2356207/Botswana_Form_Sep062018.zip)

**Comment by TNgidi** [comment]
@sbabur Thanks

**Comment by Nicolaidavies** [comment]
@sbabur The form has been updated on config version 1.0.25 on staging.

**Comment by sbabur** [comment]
@Nicolaidavies Looks good, validated, will just wait for #101 to be resolved

**Comment by sbabur** [comment]
@Nicolaidavies Hi Nicolai, apologies but I missed one skip logic in the form according to the country team! (do not need to ask about unsprayed rooms during mop-ups). Can you update the form with the attached? 

[Botswana_Form_Sep112018.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2370884/Botswana_Form_Sep112018.zip)

**Comment by Nicolaidavies** [comment]
@sbabur no problem. I updated staging to version 1.0.26.

**Comment by sbabur** [comment]
@Nicolaidavies ugh last one....had a typo

[Botswana_Form_Sep112018.zip](https://github.com/disarm-platform/user-requests-and-feedback/files/2370925/Botswana_Form_Sep112018.zip)

**Comment by Nicolaidavies** [comment]
@sbabur It's been updated, still on version 1.0.26. 

Can I ask you to get the json as "Valid json" from surveyJS editor? It saves me an extra step.

**Comment by sbabur** [comment]
@Nicolaidavies yes of course, completely forgot about that step. Everything looks good, can move to prod.

**Comment by Nicolaidavies** [comment]
@sbabur Now on production with version 1.0.26.

**Comment by sbabur** [comment]
Validated, can close
